# This is a basic workflow to help you get started with Actions

name: TestM1L9

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ M1L9 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: M1L9
                    
      
      - name: CD M1L9
        run: cd /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9 && mkdir Build && cd Build && cmake .. && cmake --build .
      #- name: mkdir Build
      #  run: mkdir /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/Build
      #- name: ls
      #  run: ls -la
      #- name: cd Build
      #  run: cd /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/Build
      #- name: ls
      #  run: ls -la
      #- name: cmake ..
      #  run: cd /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/Build && cmake ..
      #- name: cmake -- build .
      #  run: cd /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/Build && cmake --build .
      - name: ls /home
        run: ls /home
      - name: ls /home/runner
        run: ls /home/runner
      - name: ls /home/runner/work
        run: ls /home/runner/work
      - name: ls /home/runner/work/SL_Otus_basics
        run: ls /home/runner/work/SL_Otus_basics 
      - name: ls /home/runner/work/SL_Otus_basics/SL_Otus_basics
        run: ls /home/runner/work/SL_Otus_basics/SL_Otus_basics
      - name: ls /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9
        run: ls /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9
      - name: ls /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/Build
        run: ls /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/Build
        
      # Runs a set of commands using the runners shell
      - name: Run a test
        run: /home/runner/work/SL_Otus_basics/SL_Otus_basics/M1L9/bin/statistics.test
